name: meetwork
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^8.8.1
  google_fonts: ^2.0.0
  http: ^0.13.1
  image_picker: ^0.8.0+3
  json_annotation: ^4.0.1
  maps_launcher: ^1.2.2+2
  nearby_connections: ^3.0.1
  path: ^1.8.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  url_launcher: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/meetwork_logo.png

flutter_icons:
  image_path: "assets/launcher/meetwork_launcher.png"
  android: true
  ios: true
